# -*- coding: utf-8 -*-
"""analyst.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEk3_PmSbnm7BT-YS4cz13XRR5-YkhTW
"""

# Install libraries if needed:
# !pip install pandas matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# -----------------------------
# Create Sample Sales Dataset
# -----------------------------
np.random.seed(42)

dates = pd.date_range(start="2024-01-01", periods=180)
regions = ["North", "South", "East", "West"]
products = ["Laptop", "Phone", "Tablet"]

data = {
    "Date": np.random.choice(dates, 300),
    "Region": np.random.choice(regions, 300),
    "Product": np.random.choice(products, 300),
    "Sales": np.random.randint(20000, 80000, 300)
}

df = pd.DataFrame(data)
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month

# -----------------------------
# Data Analysis
# -----------------------------
total_sales = df["Sales"].sum()
sales_by_region = df.groupby("Region")["Sales"].sum()
sales_by_product = df.groupby("Product")["Sales"].sum()
monthly_sales = df.groupby("Month")["Sales"].sum()

print("Total Sales:", total_sales)
print("\nSales by Region:\n", sales_by_region)
print("\nSales by Product:\n", sales_by_product)

# -----------------------------
# Visualizations
# -----------------------------
sns.set(style="whitegrid")

plt.figure(figsize=(8,5))
monthly_sales.plot(marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.show()

plt.figure(figsize=(6,4))
sales_by_region.plot(kind="bar", color="skyblue")
plt.title("Sales by Region")
plt.ylabel("Total Sales")
plt.show()

plt.figure(figsize=(6,4))
sales_by_product.plot(kind="pie", autopct="%1.1f%%")
plt.title("Sales Distribution by Product")
plt.ylabel("")
plt.show()

# -----------------------------
# Key Insights
# -----------------------------
print("\nTop Performing Region:", sales_by_region.idxmax())
print("Top Selling Product:", sales_by_product.idxmax())
print("Best Sales Month:", monthly_sales.idxmax())